# Setup
title: Sam Welek
url: https://samwelek.co.uk
baseurl: ""
permalink: pretty

defaults:
  - scope:
      path: "_posts/blog"
    values:
      type: "blog"
  - scope:
      path: "_posts/projects"
    values:
      type: "projects"

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
ga_analytics: UA-179510239-1

# Specify the author for blog posts
author:
  name: Sam Welek
  url: https://samwelek.co.uk

# Custom vars
version: 3.0.0

# Navbar page list
nav:
  - title: Blog
    url: /blog

  - title: Projects
    url: /projects