# Setup
title: Sam Welek
tagline: My personal portfolio and blog showcasing my latest projects and guides
url: https://samwelek.co.uk
baseurl: ""
permalink: pretty

defaults:
  - scope:
      path: "_posts/blog"
    values:
      type: "blog"
  - scope:
      path: "_posts/projects"
    values:
      type: "projects"

# Gems
plugins:
  - jekyll-seo-tag
  - jemoji

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Specify the author for blog posts
author:
  name: Sam Welek
  url: https://samwelek.co.uk
  
social:
  name: Sam Welek
  links:
    - https://github.com/tiberiushunter
    - https://linkedin.com/in/sam-welek
    - https://twitter.com/samwelek

# Custom vars
version: 3.0.0

# Navbar page list
nav:
  - title: Blog
    url: /blog

  - title: Projects
    url: /projects
