# Setup
title: Sam Welek
url: https://samwelek.co.uk
baseurl: ""
permalink: pretty
lang: en_GB
twitter_username: samwelek
github_username: tiberiushunter

source: src

# Optimize Jekyll
exclude:
  - .git
  - .vscode
  - .jekyll-cache
  - node_modules
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

# Gems
plugins:
  - jekyll-seo-tag
  - jemoji

defaults:
  - scope:
      path: "_posts/blog"
    values:
      type: "blog"
  - scope:
      path: "_posts/projects"
    values:
      type: "projects"

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Specify the author for blog posts
author:
  name: Sam Welek
  url: https://samwelek.co.uk
  twitter: samwelek

social:
  name: Sam Welek
  links:
    - https://github.com/tiberiushunter
    - https://linkedin.com/in/sam-welek
    - https://twitter.com/samwelek

# Custom vars
version: 3.0.0

# Navbar page list
nav:
  - title: Blog
    url: /blog

  - title: About
    url: /about
